NH-20932: update to newest liboboe (10.6.1)
solarwindscloud/solarwinds-apm-ruby pull request #7
Opened 2022-09-21 18:35 UTC by xuan-cao-swi

## Why?
Update with liboboe 10.6.1

## Impact
1. include metric_mode config and related test
2. update the liboboe binary file location (s3)

2022-09-22 19:42 UTC, cheempz requested changes
Very exciting how quickly you're diving into things @xuan-cao-swi! A quick look seems great, but we did update the requirements around metrics yesterday so that part needs to change.  Please ping if you need more info on how that's supposed to behave.

2022-09-22 19:42 UTC, cheempz commented on lib/rails/generators/solarwinds_apm/templates/solarwinds_apm_initializer.rb
> +  SolarWindsAPM::Config[:metric_format] = 0
You were too quick for us ;). This part about exposing the format as a config option was only discussed and finalized yesterday, please see the updated description in the parent epic https://swicloud.atlassian.net/browse/NH-18852.

2022-09-23 15:56 UTC, xuan-cao-swi commented on lib/rails/generators/solarwinds_apm/templates/solarwinds_apm_initializer.rb
> +  SolarWindsAPM::Config[:metric_format] = 0
Thanks for the comments. I have hide the config option on metric_format from user.
Now it depends on the SW_APM_COLLECTOR to determine the mode

2022-09-24 00:09 UTC, cheempz reviewed
Thanks for the revisit @xuan-cao-swi!  I left some minor comments but there is a blocker in my mind regarding where the Rakefile should be updated for downloading Staging vs Prod.  Will ping you to chat on that.

2022-09-24 00:09 UTC, cheempz commented on lib/solarwinds_apm/oboe_init_options.rb
> +      # flag for format of metric (0 = AppOptics; 1 = Nighthawk, default = 0)
It's actually `(0 = Both; 1 = AppOptics only; 2 = SWO only; default = 0)`

2022-09-24 00:09 UTC, cheempz commented on lib/solarwinds_apm/oboe_init_options.rb
> +        return 0
Let's just go with the assumption that anything NOT appoptics should get metrics format 2, i.e. SWO format.  So just an "if AO, else" check is enough.

2022-09-27 19:33 UTC, xuan-cao-swi commented on lib/solarwinds_apm/oboe_init_options.rb
> +      # flag for format of metric (0 = AppOptics; 1 = Nighthawk, default = 0)
fixed

2022-09-27 19:33 UTC, xuan-cao-swi commented on lib/solarwinds_apm/oboe_init_options.rb
> +        return 0
fixed

2022-09-27 19:34 UTC, xuan-cao-swi commented on ext/oboe_metal/extconf.rb
>  # Download the appropriate liboboe from S3(via rake for testing) or files.appoptics.com (production)
changed to `OBOE_STAGING`

2022-09-27 19:35 UTC, xuan-cao-swi commented on Rakefile
> +  end
changed to only staging url

2022-09-27 19:35 UTC, xuan-cao-swi commented on CHANGELOG.md
> +* Using latest liboboe library (10.6.0)
fixed

2022-09-27 23:30 UTC, cheempz reviewed
Looking really close @xuan-cao-swi!  I gave the new `build_gem` task a spin and worked nicely :).  Left comments, many are nits, the main one being the packagecloud rake task -- not working for me and questioning how it fits into in the larger picture.  Happy to discuss in chat!

2022-09-27 23:30 UTC, cheempz commented on Rakefile
> +  system("package_cloud push solarwinds/solarwinds-apm-ruby #{gem_to_push.strip()}")
The original shellscript had a comment about credentials required that's worth moving over to this task:
`# prerequisite: package_cloud token needs to be in ~/.packagecloud`

2022-09-27 23:30 UTC, cheempz commented on Rakefile
> +end
I gave this task a try in a standard ruby:2.7 container (after installing dependencies) but it ended in:

```
# bundle exec rake build_gem_push_to_packagecloud[5.1.1]
Building native extensions. This could take a while...
Building native extensions. This could take a while...
Traceback (most recent call last):
	2: from /usr/local/bundle/bin/package_cloud:23:in `<main>'
	1: from /usr/local/lib/ruby/2.7.0/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
/usr/local/lib/ruby/2.7.0/bundler/rubygems_integration.rb:374:in `block in replace_bin_path': can't find executable package_cloud for gem package_cloud. package_cloud is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```

The gem list does show package_cloud:
```
# gem list package_cloud

*** LOCAL GEMS ***

package_cloud (0.3.10)
```

Stepping back a bit though:  there is both this rake task, and the GHA workflow to build and publish to packagecloud.  Wondering how you picture each being used, whether the logic should be consolidated if we do need both a local and GHA version (for example, GHA workflow calls this rake task), or if it's enough to just have one version.

2022-09-27 23:30 UTC, cheempz commented on ext/oboe_metal/extconf.rb
> +# Download the appropriate liboboe from S3(via rake for testing) or cloud.solarwinds.com (production)
Nit: can comment say `from Staging ... or Prod ...` instead?

2022-09-27 23:30 UTC, cheempz commented on test/run_tests/docker-compose.yml
> +  SW_APM_METRIC_FORMAT: 0
Nit remove since there is no more metric format config env var now, right?

2022-09-28 14:44 UTC, xuan-cao-swi commented on .github/workflows/build_and_release_gem.yml
>            bundle exec rake oboe_verify
fixed

2022-09-28 14:48 UTC, xuan-cao-swi commented on test/run_tests/docker-compose.yml
> +  SW_APM_METRIC_FORMAT: 0
removed

2022-09-28 14:48 UTC, xuan-cao-swi commented on ext/oboe_metal/extconf.rb
> +# Download the appropriate liboboe from S3(via rake for testing) or cloud.solarwinds.com (production)
fixed

2022-09-28 16:17 UTC, xuan-cao-swi commented on Rakefile
> +  abort("No version specified.") if args[:version].empty? || args[:version].nil?
fixed

2022-09-28 16:18 UTC, xuan-cao-swi commented on Rakefile
> +  system("package_cloud push solarwinds/solarwinds-apm-ruby #{gem_to_push.strip()}")
added the msg

2022-09-28 16:36 UTC, xuan-cao-swi commented on Rakefile
> +end
it seems like there is ruby version mismatch between `bundle exec ruby` vs `ruby`

2022-09-28 17:24 UTC, xuan-cao-swi commented on Rakefile
> +end
I never run build_for_packagecloud.yml action, not sure if it works.
I can test it out and see if these two tasks can be merged.

2022-09-29 21:22 UTC, cheempz commented on Rakefile
> +  remote_file = File.join("https://agent-binaries.cloud.solarwinds.com/apm/c-lib/latest", 'VERSION')
Indeed! Let's ask @jerrytfleung if a "latest version" file can be written to help with this use case.

2022-09-29 21:36 UTC, cheempz commented on Rakefile
> +end
Per our discussion, it would be helpful to be able to build/publish to packagecloud both locally and via GHA.  So let's see if we can move the `package_cloud` gem dependency to main Gemfile, and consolidate logic.

2022-09-29 21:38 UTC, cheempz commented on CHANGELOG.md
>  This patch release includes the following fixes:
Nit let's call this `includes the following features`

2022-09-29 22:16 UTC, jerrytfleung commented on Rakefile
> +  remote_file = File.join("https://agent-binaries.cloud.solarwinds.com/apm/c-lib/latest", 'VERSION')
Done

2022-09-30 15:16 UTC, xuan-cao-swi commented on Rakefile
> +  remote_file = File.join("https://agent-binaries.cloud.solarwinds.com/apm/c-lib/latest", 'VERSION')
Thanks @jerrytfleung , the permission seems not set
https://ssp-stage-global-agent-binaries.s3.amazonaws.com/apm/c-lib/latest/VERSION
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>G2423JEXWPAMX4VX</RequestId>
<HostId>Xlv4qMYsDTu74B9CwEOfUjmUW6VVGo3FOry3njLJecdriyQpDxCPsyoce09OdpPiGHnLl6zcQ0U=</HostId>
</Error>
```

2022-09-30 16:01 UTC, xuan-cao-swi commented on Rakefile
> +  remote_file = File.join("https://agent-binaries.cloud.solarwinds.com/apm/c-lib/latest", 'VERSION')
Hi @jerrytfleung , it seems like everything got access denied.
https://agent-binaries.global.st-ssp.solarwinds.com/apm/c-lib/10.6.1/include/bson/bson.h

2022-09-30 16:49 UTC, jerrytfleung commented on Rakefile
> +  remote_file = File.join("https://agent-binaries.cloud.solarwinds.com/apm/c-lib/latest", 'VERSION')
Please retry. I missed to execute public read access yesterday

2022-09-30 17:28 UTC, xuan-cao-swi commented on CHANGELOG.md
>  This patch release includes the following fixes:
fixed

2022-09-30 17:29 UTC, xuan-cao-swi commented on Rakefile
> +  remote_file = File.join("https://agent-binaries.cloud.solarwinds.com/apm/c-lib/latest", 'VERSION')
@jerrytfleung thanks!

2022-09-30 18:36 UTC, cheempz approved these changes
Thanks for the revisits and build+publish consolidation @xuan-cao-swi!

2022-10-01 02:40 UTC, merged